version: "3.8"

services:
  web:
    container_name: dockerdev
    build: ./
    ports:
      - "8000:8000"
    environment:
      DD_DB_HOST: db
    command: /server
    depends_on:
      - db
  db:
    container_name: dockerdev-sql
    image: mysql:5.7.30
#    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE": dataset
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"